[package]
name = "r-efi-lib"
version = "0.1.0"
authors = ["Xiaoyu Lu <xiaoyux.lu@intel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r-efi = { path = "../../External/r-efi"}
r-efi-str = { path = "../../External/r-efi-str" }
log = "0.4.8"
ucs2 = { version = "0.3.1"}